name: Lint Dockerfile

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/lint.yml
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/lint.yml
  workflow_dispatch:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Run hadolint
        run: |
          docker run --rm -v "$PWD":/work -w /work \
            hadolint/hadolint:v2.15.1-alpine@sha256:a1d49ae1a4e83c1dbad26b8c1ad7588c8bd1e04f4866b34ad3cac50335198552 \
            sh -c "hadolint --version && hadolint Dockerfile"
